######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 22:13:31 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MySetting.h
SOURCES += Main.cpp
